#!/bin/bash

handle_error() {
    trap '' ERR
    local frame=0 str
    local stacktrace="Command exited with status $1\n\nStack:"
    while str=$(caller $frame); do
        stacktrace+="\nline $str"
        frame=$((frame+1))
    done
    notify-send -u critical "hlwm config error" "$stacktrace"
}
set -o errtrace
trap 'handle_error $?' ERR

hc() {
    herbstclient "$@"
}


is_first_start() {
    ! hc silent get_attr my_loaded 2>/dev/null
}

hc emit_hook reload

xsetroot -solid '#000000'

hc set wmname LG3D

xset s 300 600 &
xss-lock -- /usr/bin/i3lock -c 000000 &

# Keybindings
. "$HOME"/.config/herbstluftwm/keyBinds 
# Theme
. "$HOME"/.config/herbstluftwm/theme


# tags
tag_names=( {1..9} 0 scratchpad )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# rules
hc unrule -F
hc rule focus=on # normally do not focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

herbstclient set tree_style '╾│ ├└╼─┐'

hc attr settings.auto_detect_panels 0
hc detect_monitors


if is_first_start; then
	hc new_attr bool my_loaded true
	xset +fp /home/boerta/.local/share/fonts
	xset fp rehash
	dunst &
	mate-power-manager &
	nm-applet &
	naisdevice &
	flameshot &
	blueman-applet &
	lxqt-policykit-agent &
   # start-pulseaudio-x11
fi


if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi


#if hc silent new_attr bool my_not_first_autostart ; then
#    blueman-applet &
#    nm-applet &
#    #~/.config/herbstluftwm/qas.sh
#    flameshot &
#    naisdevice &
#    discord &
#    slack &
#    firefox &
#    intellij-idea-ultimate &
#    #google-chrome &
#fi

for monitor in $(hc list_monitors | cut -d: -f1) ; do
    ~/private/barpyrus/barpyrus.py $monitor &
done

hc unlock
